### ISSUE TITLE
Visible Sat. and Locked Sat. count calculation

### ISSUE THREAD

**Issue by neekersen** [RenanRB/satellities_TLE#1]
Renan, hello,
I am Emre Taşkıran from the Ne Ekersen team.

First of all, I congratulate you for your work and wish you continued success. I want to say that DroneWeather is very successful.

1) What kind of math do you do in the "Visible Sat." and "Locked Sat." parts of the application? How do you calculate "Visible Sat." and "Locked Sat." using the Json in this Repo?

2) And my last question is; what do you mean by "Locked Sat."?

Thanks.
Emre.

**Comment by RenanRB** [comment]
Hi, I currently use the library: https://github.com/jhermsmeier/node-tle
I send it the json file information and the date, so this lib returns the number of available satellites.
The part about blocked satellites is a little more complex and is not very precise, to make this calculation I do some internal calculations taking into account the total available, the KP index and the degree of inclination.

Blocked satellites would be the maximum number that the drone's GPS can use, even though there are 20 satellites available (just an example) it will not be all that the drone will be able to use, as it will depend on the altitude the drone is at and the KP index. of that moment.
